#!/bin/sh /etc/rc.common
# Copyright (C) 2026 wsburrow project
# Init script for wsburrow reverse tunnel client

USE_PROCD=1
START=95
STOP=01

start_service() {
    local server_url arguments
    
    config_load 'wsburrow'
    config_get server_url 'main' 'server_url'
    config_get arguments 'main' 'arguments'
    
    [ -z "$server_url" ] && {
        logger -t wsburrow "ERROR: server_url not configured in /etc/config/wsburrow"
        return 1
    }
    
    procd_open_instance
    procd_set_param command /usr/bin/wsburrow
    procd_append_param command $arguments
    procd_append_param command $server_url
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # procd handles this automatically
    :
}

service_triggers() {
    procd_add_reload_trigger 'wsburrow'
}
